apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: gw
      meta.helm.sh/release-namespace: aws-ec2-akeyless-namespace
    creationTimestamp: "2024-02-11T13:52:46Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: gw
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: akeyless-api-gateway
      app.kubernetes.io/version: 3.61.0
      helm.sh/chart: akeyless-api-gateway-1.38.0
    name: gw-akeyless-api-gateway
    namespace: aws-ec2-akeyless-namespace
    resourceVersion: "59645"
    uid: fb6545bc-0b09-4dca-a5e0-1c75fdd9f1fe
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: gw
        app.kubernetes.io/name: akeyless-api-gateway
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: gw
          app.kubernetes.io/name: akeyless-api-gateway
      spec:
        containers:
        - env:
          - name: ADMIN_ACCESS_ID
            valueFrom:
              secretKeyRef:
                key: admin-access-id
                name: gw-conf-secret
          - name: RESTRICT_ACCESS_TO_ADMIN_ACCOUNT
            value: "true"
          - name: UID_ROTATE_INTERVAL
            value: 5m
          - name: UID_CREATE_CHILD_TOKEN_PER_POD
            value: disable
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: VERSION
            value: 3.61.0
          image: akeyless/base:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          name: api-gateway
          ports:
          - containerPort: 18888
            name: web
            protocol: TCP
          - containerPort: 8000
            name: configure-app
            protocol: TCP
          - containerPort: 8080
            name: legacy-api
            protocol: TCP
          - containerPort: 8081
            name: api
            protocol: TCP
          - containerPort: 8200
            name: hvp
            protocol: TCP
          - containerPort: 5696
            name: kmip
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default
        serviceAccountName: default
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2024-02-11T13:52:47Z"
      lastUpdateTime: "2024-02-11T13:55:17Z"
      message: ReplicaSet "gw-akeyless-api-gateway-597d9f78b4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-02-11T14:21:19Z"
      lastUpdateTime: "2024-02-11T14:21:19Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
