apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-db
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-user
                key: root_password
          - name: MYSQL_DATABASE
            value: db
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-user
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-user
                key: password
          image: mysql:latest
          name: mysql-db
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: my-db-pvc
      restartPolicy: Always
      volumes:
        - name: my-db-pvc
          persistentVolumeClaim:
            claimName: my-db-pvc
status: {}
