---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-db-pv
  labels:
    storage: my-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/my-db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: my-db
    storage: my-db
  name: my-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
