apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-db
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - image: mysql:latest
          name: mysql-db
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          - name: MYSQL_DATABASE
            value: db
          - name: MYSQL_PASSWORD
            value: letmein
          - name: MYSQL_USER
            value: shay.m
          
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: my-db
            mountPath: /var/lib/mysql
      restartPolicy: Always      
      volumes:
      - name: my-db
        persistentVolumeClaim:
          claimName: my-db-pvc
status: {}
