apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
    app: mysql-db
  name: db
spec:
  ports:
    - name: "3306"
      protocol: TCP
      port: 3306
  selector:
    service: db
    app: mysql-db
